DjangoServer/src/DjangoServer/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'DjangoServer.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^(?i)DataCollection/', include('DataCollection.urls',namespace="DataCollection")),
    url(r'^(?i)admin/', include(admin.site.urls)),
    url(r'^(?i)survey/',include('survey.urls',namespace="survey")),
    url(r'^(?i)cyber-bullying/', include('DataCollection.urls',namespace="cyber-bullying")),
)

DjangoServer/src/survey/urls.py
'''
Created on May 28, 2014

@author: maxclapp
'''
from django.conf.urls import patterns, url

from survey import views


urlpatterns = patterns('',
    url(r'^(?i)(?P<survey_id>\d+)/(?P<user_id>-?\d+)/$', views.survey,name='survey'),
   url(r'^(?i)(?P<survey_id>\d+)/(?P<user_id>-?\d+)/answer/$', views.answer,name='answer'),
   url(r'^(?i)(?P<survey_id>\d+)/results/$', views.results,name='results'),
   url(r'^(?i)(?P<survey_id>\d+)/(?P<user_id>-?\d+)/email/$', views.email,name='email'),
   url(r'^(?i)(?P<survey_id>\d+)/(?P<user_id>-?\d+)/sendemail/$', views.sendemail,name='sendemail'),
   url(r'^(?i)refresh/$', views.refresh,name='refresh'),
)

DjangoServer/src/survey/models.py
'''
Created on May 23, 2014

@author: maxclapp
'''
from django.db import models
from django.utils import timezone

choices = {
           (0,"Short answer"),
           (1,"Multiple choice pick one"),
           (2,"Multiple choice pick all that apply"),
           }

class Survey(models.Model):
    title = models.CharField(max_length = 150)
    created_date = models.DateTimeField('Date to be given on',default = timezone.now())
    def __unicode__(self):
        return self.title

class Question(models.Model):
    atype = models.IntegerField("Answer type",choices = choices, default = 0)
    text = models.CharField("Question",max_length = 1000)
    answer = models.CharField(max_length = 500,default = "0")
    survey = models.ForeignKey(Survey)
    def __unicode__(self):
        return self.text
    
class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=500)
    def __unicode__(self):
        return self.choice_text
    

DjangoServer/src/survey/forms.py
'''
Created on May 28, 2014

@author: maxclapp
'''
# from django import forms
# from django.forms.models import inlineformset_factory
# from servey.models import Servey,SingleChoiceQuestion,Choice
#       
# class singleQuestionForm(forms.Form):
#     def __init__(self,*args,**kwargs):
#         choices = kwargs.pop('my_choices')
#         super(singleQuestionForm,self).__init__(*args, **kwargs)
#         self.fields['answer'] = forms.Select(choices = choices)
#     text = forms.CharField()

DjangoServer/src/survey/views.py
'''
Created on May 23, 2014

@author: maxclapp
'''
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect,HttpResponse
from django.shortcuts import get_object_or_404,render
from django.core import serializers
from .models import Survey, Question,Choice
from DataCollection.models import User, SurveyData, UpdatedDate
from django.core.mail import send_mail
import json
import subprocess


def refresh(request):
    subprocess.call(['java','-jar','/home/clapp/Documents/DataCollectionJava/server-side-collection/collectAllData.jar'])
    return HttpResponse("Updateing facebook ")

def survey(request , survey_id , user_id):
    user = get_object_or_404(User, pk = user_id )
    date = get_object_or_404(UpdatedDate, user = user )
    survey = get_object_or_404(Survey, pk = survey_id )
    return render(request , 'survey/survey.html',{'survey':survey,'user_id':user_id, 'date':date})
    
def sendemail(request,survey_id,user_id):
    text = request.POST["textbox"]
    text = text + "\n \n user_id " + str(user_id) + "\n \nsurvey_id " + str(survey_id)
    send_mail("DATA ERROR" ,text,"cyber-bullying@uiowa.edu",["llclaptrapll@gmail.com"])
    return HttpResponse("Thank you problem will be taken care of asap")

def answer(request,survey_id,user_id):
    survey = get_object_or_404(Survey, pk = survey_id )
    for question in survey.question_set.all():
        if int(question.atype) == 1:
            try:
                choice_id = request.POST[str(question.id)]
                answer = question.choice_set.get(pk=choice_id)
            except (KeyError, Choice.DoesNotExist):
                return render(request, 'survey/survey.html',{'survey':survey,
                                                         'error_message': "Please fill out full survey befor submiting."})       
            else:
                question.answer = answer.choice_text
                question.save()
        if int(question.atype) == 2:
            choice_list = request.POST.getlist(str(question.id))
            choices = ""
            for choice_id in choice_list:
                try:
                    answer = question.choice_set.get(pk=choice_id)
                except (KeyError, Choice.DoesNotExist):
                    return render(request, 'survey/survey.html',{'survey':survey,
                                                         'error_message': "Please fill out full survey befor submiting."})       
                else:
                    if choices:#checks to see if it is empty (empty sting is false)
                        choices += "+"
                        choices += answer.choice_text
                    else:
                        choices += answer.choice_text
            question.answer = str(choices.split("+"))
            question.save()
        
        if int(question.atype) == 0:
            question.answer = request.POST[str(question.id)]
            question.save()
    jsonData = serializers.serialize("json",survey.question_set.all())
    qs = survey.question_set.filter(answer = "No")
    if qs:
        return HttpResponseRedirect(reverse('survey:email', args=(survey.id,user_id)))
    try:
        user = User.objects.get(phone_number = user_id)
        surveydata_object = SurveyData.objects.get(user = user)
        surveydata_string=surveydata_object.surveydata
        adddata = eval(str(surveydata_string))
        adddata[str(survey.id)]=str(jsonData)
        surveydata_object.surveydata = str(adddata)
        surveydata_object.save()
    except:
        import traceback
        exception = traceback.format_exc()
        print exception
        send_mail("DATA ERROR" ,exception,"cyber-bullying@uiowa.edu",["llclaptrapll@gmail.com"])
        return render(request,'DataCollection/fail.html')
    return HttpResponseRedirect(reverse('survey:results', args=(survey.id,)))

def results(request,survey_id):
    survey = get_object_or_404(Survey, pk = survey_id )
    return render(request,'survey/results.html',{'survey':survey})    
            
def email(request,survey_id,user_id):
    return render(request,'survey/email.html',{'survey_id':survey_id,
                                                "user_id":user_id})    

DjangoServer/src/survey/templates/survey/email.html
<!doctype html>
<html>
<head>
<meta name="viewport" content= "width=device-width, inital-scale=1.0"/>

</head>

<form action="{% url 'survey:sendemail' survey_id  user_id %}" method="post">
{% csrf_token %}
<pre>Please briefly describe the data was missing</pre>
<textarea name = "textbox" id = "textbox"></textarea><br />
<input type="submit" value="Submit" />
</form>

</html>

DjangoServer/src/survey/templates/survey/results.html
<!doctype html>
<html>
<head>
<meta name="viewport" content= "width=device-width, inital-scale=1.0"/>
<script>
setTimeout(function(){
    self.close();
},3000);
</script>
</head>


<h1>{{ survey.title }}</h1>

<ul>
{% for question in survey.question_set.all %}
    <li>{{ question.text}} -- {{question.answer}}</li>
{% endfor %}
</ul>
<html>

DjangoServer/src/survey/templates/survey/survey.html
<!doctype html>
<html>
<head>
<meta name="viewport" content= "width=device-width, inital-scale=1.0"/>
<script>
function validateForm() {
	var elem = document.getElementById('questions').elements;
	var allQ = []
	var checkedQ = []
    for(var i = 0; i < elem.length; i++){
		if(elem[i].type == "radio"){
			allQ.push(elem[i].name)
            if ( elem[i].checked ){
					checkedQ.push(elem[i].name)
			}
}	}
	if (!(((allQ.length/2) == checkedQ.length) && (checkedQ.length != 0))){
		alert("All questions must be filled out before submiting");
        return false;
		}
}
</script>
<!-- Bootstrap,CSS,JQuery,BootstrapJavaScript -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<body>
        <!-- BODY CONTENT DOWN HERE -->
        <div class="page">
        
        <div id="content">
            
        <div class="splash-screen">
            <div class="container">
                <div class="row">
                    <div class="col-md-9">
                                <h1>Data collected within the past 24 hours</h1>
				<h3>User: {{user_id}} </h3>
                                <h3>{{survey.title}}</h3>
                                <h4>"Facebook last updated {{ date.facebookDate }}"</h4>
                                <h4>"Text messages last updated {{ date.smsDate }}"</h4>
                                <h4>"Twitter last updated {{ date.twitterDate }}"</h4>
                    </div>
                    <div class="col-md-3">
                    </div>
                </div>
                <hr/>
            </div>
        </div>
        <form id= 'questions' name ='questions' method='POST' onsubmit="return validateForm()" action= "{% url 'survey:answer' survey.id user_id %}">
        {% csrf_token %}
        {% for  question in survey.question_set.all %}
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">  
                            <div class="panel panel-info">
                                <div class="panel-heading">
                                    <h3 class="panel-title">
                                        <i class="fa fa-bullhorn"></i> Collection subset
                                    </h3>
                                </div>
                                <div class="panel-body">
				    <pre>{{ question.text }}</pre>
                                    {% if question.atype == 0 %}
                                        <textarea name = "{{ question.id }}" id = "{{ question.id}}">
                                        </textarea><br />
                                    {% endif %}
               
                                    {% if question.atype == 1 %}
                                        {% for choice in question.choice_set.all %}
                                  
                                            <input type="radio" name="{{ question.id }}" id="choice{{ forloop.counter }}{{ forloop.parentloop.counter}}" value="{{ choice.id }}" />
                                            <label for="choice{{ forloop.counter }}{{ forloop.parentloop.counter}}">{{ choice.choice_text }}</label><br />
                                        {% endfor %}
                                    {% endif %}
                
                                    {% if question.atype == 2 %}
                                        {% for choice in question.choice_set.all %}
                                            <input type="checkbox" name="{{ question.id }}" id="choice{{ forloop.counter }}{{ forloop.parentloop.counter}}" value="{{ choice.id }}" />
                                            <label for="choice{{ forloop.counter }}{{ forloop.parentloop.counter}}">{{ choice.choice_text }}</label><br />
                                        {% endfor %} 
                                    {% endif %}
                                </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        
        </div>
    </div>
<!-- END BODY CONTENT HERE -->
<input type="submit" value="Submit" />
</form>
</html>