DjangoServer/src/DataCollection/urls.py
from django.conf.urls import patterns, url
from DataCollection import views
from DataCollection import new_user_views
from DataCollection import data_post_views

urlpatterns = patterns('',
	url(r'^$', views.mainPage, name='mainPage'),
	url(r'^(?i)postandroid/$',          data_post_views.postandroid, name='postandroid'),
	url(r'^(?i)instructions/$',         views.instructions, name='insturctions'),
	url(r'^(?i)gethelp/$',              views.getHelp, name='gethelp'),
	url(r'^(?i)newtoken/$',             views.newToken, name='newToken'),
	url(r'^(?i)withdraw/$',             views.withdraw, name='withdraw'),
	url(r'^(?i)survey/$',               views.survey, name='survey'), 
	url(r'^(?i)getfacetoken/$' ,        views.get_all_faceid , name= 'getfacetoken' ),
	url(r'^(?i)gettwittertoken/$' ,     views.get_all_twitter , name= 'gettwittertoken' ),
	url(r'^(?i)postfacebook/$' ,        data_post_views.facebook_post , name= 'facebookpost' ),
	url(r'^(?i)posttwitter/$' ,         data_post_views.twitter_post , name= 'twitter' ),
	url(r'^(?i)posttwitterseparate/$' , data_post_views.twitter_post_separate , name= 'twitterSeparatepost' ),
	url(r'^(?i)makeuser/$' ,            new_user_views.make_user , name= 'makeuser' ),
	url(r'^(?i)unifycollect/$' ,        views.unify_collect, name= 'unifycollect' ),
	url(r'^(?i)getalluser/$' ,          views.get_all_user, name= 'getalluser' ),
	url(r'^(?i)app/$',                  views.app , name='app'),
	url(r'^(?i)facebookbackend/$' ,     new_user_views.facebookLoginBackend, name= "facebookbackend"),
	url(r'^(?i)twittercallback/$' ,     new_user_views.twitterCallBack),
	url(r'^(?i)emailbackend/$' ,        new_user_views.emailBackend, name= "emailbackend"),
	url(r'^(?i)login/$' ,               new_user_views.emailLogin),
	url(r'^(?i)twitterlogin/$',         new_user_views.twitterLogin, name= "twitterlogin"),
	url(r'^(?i)notwitter/$',            new_user_views.noTwitter, name= "notwitter"),
	url(r'^(?i)resources/$',            views.resources, name='resources'),
	url(r'^(?i)surveylogin/$',          views.surveyLogin, name= "surveylogin"),
	url(r'^(?i)startlogin/$',           views.startLogin, name= "startlogin"),
	url(r'^(?i)surveyiphoneloginbackend/$', views.surveyIphoneBackend, name= "surveyiphoneloginbackend"),
	url(r'^(?i)surveyphonebackend/$',           views.surveyPhoneBackend, name= "surveyphonebackend"),
	url(r'^(?i)sendoutsurvey/$',        views.sendOutSurvey, name= "sendoutsurvey"),
	url(r'^(?i)sendemail/$',            views.sendEmail, name= "sendemail"),
	url(r'^(?i)generateUserDeltas/$',   views.generateUserDeltas, name = "generateUserDeltas"),
	url(r'^(?i)iphoneback/$',           new_user_views.iphoneBackEnd, name= "iphoneBackEnd"),
	url(r'^(?i)iphoneloginbackend/$',   new_user_views.iphoneLoginBackend, name= "iphoneloginbackend"),
	url(r'^(?i)faculty/$',              views.faculty, name="faculty"),
	url(r'^(?i)text/$',                 views.text, name="text"),
	url(r'^(?i)textbackend/$',          views.textBackend, name="textbackend"),
	url(r'^(?i)privacy/$',		        views.privacy, name="privacy"),
	url(r'^(?i)webwithdraw/$',		    views.web_withdraw, name="webwithdraw"),
	url(r'^(?i)webwithdrawbackend/$',	views.web_withdraw_backend, name="webwithdrawbackend"),
)

DjangoServer/src/DjangoServer/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'DjangoServer.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^(?i)DataCollection/', include('DataCollection.urls',namespace="DataCollection")),
    url(r'^(?i)admin/', include(admin.site.urls)),
    url(r'^(?i)survey/',include('survey.urls',namespace="survey")),
    url(r'^(?i)cyber-bullying/', include('DataCollection.urls',namespace="cyber-bullying")),
)

DjangoServer/src/survey/urls.py
'''
Created on May 28, 2014

@author: maxclapp
'''
from django.conf.urls import patterns, url

from survey import views


urlpatterns = patterns('',
    url(r'^(?i)(?P<survey_id>\d+)/(?P<user_id>-?\d+)/$', views.survey,name='survey'),
   url(r'^(?i)(?P<survey_id>\d+)/(?P<user_id>-?\d+)/answer/$', views.answer,name='answer'),
   url(r'^(?i)(?P<survey_id>\d+)/results/$', views.results,name='results'),
   url(r'^(?i)(?P<survey_id>\d+)/(?P<user_id>-?\d+)/email/$', views.email,name='email'),
   url(r'^(?i)(?P<survey_id>\d+)/(?P<user_id>-?\d+)/sendemail/$', views.sendemail,name='sendemail'),
   url(r'^(?i)refresh/$', views.refresh,name='refresh'),
)

DjangoServer/src/DataCollection/views.py
from DataCollection.models import User, twitter_direct_conversation, \
    twitter_conversation, twitter_message, sms_conversation, userInfo, \
    twitter_status, facebook_conversation, facebook_messages, facebook_comments, \
    sms_message,SurveyData,UpdatedDate,facebook_activity,facebook_likes
from survey.models import Survey,Question,Choice
from django.shortcuts import render,get_object_or_404
from django.core import serializers
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.http.response import StreamingHttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils import simplejson, encoding, timezone
from django.core.mail import EmailMessage
from DjangoServer import settings
from django.core.urlresolvers import reverse
from googlevoice import Voice


#from DataCollection import new_user_views, date_post_views


import re
import json
import datetime
import requests
from twython import Twython


from simplecrypt import encrypt,decrypt
import simplecrypt
from dateutil import parser
from threading import Thread


from hashlib import md5
from Crypto.Cipher import AES
from Crypto import Random
import os

import new_user_views


ip = 'http://alacran.cs.uiowa.edu/'
key = settings.KEY
facebookAppId = settings.FACEAPP_ID
facebookSecret = settings.FACE_SECRET
APP_KEY = settings.TWITTER_CONSUMER_KEY
APP_SECRET = settings.TWITTER_CONSUMER_SECRET
OAUTH_TOKEN = ''
OAUTH_TOKEN_SECRET = ''
tempEmail = ''
tempToken = ''
tempPhone = ''

@csrf_exempt
def getHelp(request):
    print request.GET
    return HttpResponse("temp page and url for quick testing")

def sendSMS(number, message):
    user = settings.GVOICE
    password = settings.GVOICE_PASS
    voice = Voice()
    voice.login(user, password)
    voice.send_sms(number, message)

@csrf_exempt
def sendText(user_list, message):
    for user in user_list:
        sendSMS(decrypt(key, user.encrypted_number) , message)

@csrf_exempt
def text(request):
    return render(request, 'DataCollection/sendText.html')

@csrf_exempt
def textBackend(request):
    try:
        number = User.objects.all()
        if request.POST["phone"]:
            number = [User.objects.get(phone_number = hash(str(re.sub("[^0-9]", "",request.POST["phone"]))))]
        if not request.POST["email"]:
            message = "http://alacran.cs.uiowa.edu/DataCollection/startlogin"
        else:
            message = str(request.POST["email"])
        sendText(number, message)
        return HttpResponse("text message was sent")
    except:
        return fail(request,"Text backend failure")

@csrf_exempt
def surveyPhoneBackend(request):
    try:
        tempPhone = str(request.POST["phone"])
        tempPhone = re.sub("[^0-9]", "",tempPhone)
        return render(request , 'DataCollection/surveyLogin.html',{'phone_number':tempPhone})
    except:
        return fail(request,"email backend failure")
    
@csrf_exempt
def surveyIphoneBackend(request):
    phone_number = request.GET["phone_number"]
    return render(request, 'DataCollection/surveycallback.html',{'phone_number': phone_number})

@csrf_exempt
def surveyLogin(request):
    try:
        phone_number = request.POST["phone_number"]
        hphone_number = hash(phone_number)
        temp = str(request.POST["token"]).split("&")
        if "#" in temp[0]:
            temp = temp[0].replace("#access_token=","")
        else:
            temp = temp[0].replace("access_token=","")
        accessTokenRequestString = 'https://graph.facebook.com/oauth/access_token?grant_type=fb_exchange_token&client_id='+ facebookAppId + '&client_secret='+ facebookSecret + '&fb_exchange_token=' + temp
        facebookResponse= requests.get(accessTokenRequestString)
        facebookResponse = facebookResponse.text
        L = facebookResponse.split("&")
        tempToken = L[0].replace("access_token=","")
        user = User.objects.get(phone_number = hphone_number)
        user.facebook_token = tempToken
        user.save()
        date = get_object_or_404(UpdatedDate, user = user )
        survey = buildSurvey(user,hphone_number)
        return render(request , 'survey/survey.html',{'survey':survey,'user_id':hphone_number, 'date':date})
    except:
        return fail(request,"survey login failure")


@csrf_exempt
def generateUserDeltas(request):
    try:
        all_users = User.objects.all()
        try:
            saved_file = open("/home/clapp/Documents/DataCollectionDjango/DjangoServer_CyberBullying/DjangoServer/src/jsonDump/phone_num_diffs.txt", "r")
            lines = saved_file.readlines()
        except:
            lines = []
        not_updated = []
        new_users = []

        # Go through all the users
        for user in all_users:
            # Get the user's information
            date_details = UpdatedDate.objects.get(user = user)
            num = decrypt(key, user.encrypted_number)
            date = date_details.smsDate
            found = False
            # Go through the file and get the info
            for i, line in enumerate(lines):
                file_num = line.split(",")[0]
                file_date = line.split(",")[1]
                # If the file number equals the user's number
                if (file_num == num):
                    found = True
                    # update the file with the new date from the database
                    lines[i] = file_num + "," + str(date)
                    
                    if date == None or len(str(num)) == 0: # A non cell phone user
                        pass
                    elif (date < timezone.now() - datetime.timedelta(hours = 48)):
                        # If the last time the user was updated was more than 48 hours ago
                        not_updated.append(file_num)
            if not found and date != None and len(num) != 0: # If we didn't find them they're a new user and we need to add them
                lines.append(num + "," + str(date))
                new_users.append(num)

        saved_file = open("/home/clapp/Documents/DataCollectionDjango/DjangoServer_CyberBullying/DjangoServer/src/jsonDump/phone_num_diffs.txt", "w")
	for line in lines:
            saved_file.write(line + "\n")
        email = ""
        email += "New: \n"
        for user in new_users:
                email +=  "\t" + str(user) + "\n"
        email += "Not Updated in the last 48 hours: \n"
        for user in not_updated:
                email +=  "\t" + user + "\n"
        saved_file.close()

#-------------------------------
#   The last updated part
        email += "\n\n\n"
        email += "The last updated times for users\n"
        test_users = ['4103953963257201570','-8559265015842739200', '296267656718926475', '2103970963504202057', '-2850050825785764042','-2453938116241190695','-142739595837066840']
        for dateObj in UpdatedDate.objects.all():
            if dateObj.user_id not in test_users:
                email +=  "User: " + str(dateObj.user_id)
                email +=  "\tFacebook Last Updated: " + str(dateObj.facebookDate)
                if dateObj.twitterDate != parser.parse("2014-12-12"):
                        email += "\tTwitter Last Updated: " + str(dateObj.twitterDate)
                if dateObj.smsDate != parser.parse("2014-12-12"):
                        email += "\tSMS Last Updated: " +str(dateObj.smsDate)

#-------------------------------
        print email
        send_mail("New users and those who haven't updated in 48 hours",email,'cyber-bullying@uiowa.edu', to=["tomwer3@gmail.com"]) #"rebecca-bruening@uiowa.edu","tom-werner@uiowa.edu","dominica-rehbein@uiowa.edu", "octav-chipara@uiowa.edu"])
    except:
        return fail(request,"Error generating user deltas")

    return HttpResponse(email)#render(request, 'DataCollection/thanks.html')
#end def

@csrf_exempt
def sendSurvey(user_list):
    var = []
    try:
        for x in user_list:
            if(x.email):
                var.append(x.email)
        send_mail('Cyber-Bullying Survey','Click the link to start you cyber-bullying survey. http://alacran.cs.uiowa.edu/DataCollection/startlogin/','cyber-bullying@uiowa.edu', to=var)
    except:
        return fail(None,"send survey failure")
    

@csrf_exempt
def sendOutSurvey(request):
    pass
    
  


@csrf_exempt
def newToken(request):
    try:
        data=json.loads(unicode(request.body, errors='replace'))
        user = User.objects.get(phone_number = data.get("user"))
        user.facebook_token = data.get("facebook_token")
        user.save()
        return HttpResponse("worked")
    except:
        print "new token"
        return HttpResponse("null")

@csrf_exempt
def withdraw(request):
    try:
        data=json.loads(unicode(request.body, errors='replace'))
        phone = data.get("user")
        if User.objects.filter(phone_number = hash(phone)):
            user = User.objects.filter(phone_number = hash(phone))
            if UpdatedDate.objects.filter(user = user):
                D = UpdatedDate.objects.get(user = user)
                D.twitterDate = datetime.datetime(2020,1,1)
                D.facebookDate = datetime.datetime(2020,1,1)
                D.save()
    except:
        HttpResponse("sorry try again later")
    return HttpResponse("Your out")
        
@csrf_exempt
def web_withdraw(request):
    return render(request , 'DataCollection/withdraw.html')
    
@csrf_exempt
def web_withdraw_backend(request):
    phone = request.body[6:]
    if User.objects.filter(phone_number = hash(phone)):
        user = User.objects.filter(phone_number = hash(phone))
        if UpdatedDate.objects.filter(user = user):
            D = UpdatedDate.objects.get(user = user)
            D.twitterDate = datetime.datetime(2020,1,1)
            D.facebookDate = datetime.datetime(2020,1,1)
            D.save()
            return render(request, 'DataCollection/withdraw_thanks.html')
    
    return render(request, 'DataCollection/withdraw_fail.html')

DjangoServer/src/DataCollection/templates/DataCollection/downloadApp.html
<!DOCTYPE html>
<html>
<body>
<meta name="viewport" content= "width=device-width, inital-scale=1.0"/>
<p>This is version 0.9 of the uiowa cyberbullying project. </p> 
<a href = "/static/smsRead.apk">Download Test App</a>
</body>
</html>

DjangoServer/src/DataCollection/templates/DataCollection/email.html
<!DOCTYPE html>
<html>
<head>
<title>Login Email</title>
<meta charset="UTF-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Bootstrap,CSS,JQuery,BootstrapJavaScript -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}/email.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="http://jqueryvalidation.org/files/dist/jquery.validate.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/additional-methods.js"></script>
<script>
   
    $(document).ready(function(){
        $(".popover-top").popover({
            placement : 'top'
        });});
    $(document).ready(function(){ 
         $("#emailForm").validate({
            rules: {
                email: {
                    required: true,
                    email: true
                },
                phone:{
                    required: true,
                    phoneUS: true
                }
            }
        });
    });
 $('html').on('click', function(e) {
  if (typeof $(e.target).data('original-title') == 'undefined' &&
     !$(e.target).parents().is('.popover.in')) {
    $('[data-original-title]').popover('hide');
  }
});
</script>
</head>
<body>

<div class="container">
    <div class="alert-message"></div>
    <div class="panel panel-default login-panel">
        <div class="panel-heading"><h1>Cyberbullying Registration</h1></div>
        <div class="panel-body">
            <div class="brand">
                <img class="img img-icon" src="{{ STATIC_URL }}/uiowaLogo.png" alt="University of Iowa Logo">
            </div>
            <div class="form-container">
                <form id="emailForm" name="loginForm" class="form-signin" method="post" action="{% url 'DataCollection:emailbackend'%}" >
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input name="email" type="email" class="form-control" id="email" autofocus="">
						<label for="phone">Cell Phone</label>
                        <input name="phone"  placeholder="(xxx)xxx-xxxx" class="form-control" id="phone" autofocus="">
                    </div>
                    <input type="submit" name="uip_action" value=" Continue " class="btn btn-primary login-button">
                    <div class="help-text">
                        <a href="#" class="popover-top" data-toggle="popover" title="Email" data-content="Your email will be used as an ID and to send surveys.">Why do I need to provide my email?</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="custom-text"></div>
</div>
</body></html>

DjangoServer/src/DataCollection/templates/DataCollection/facebookTest.html
<!DOCTYPE html>
<html>
<head>
<title>Login JavaScript</title>
<meta charset="UTF-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Bootstrap,CSS,JQuery,BootstrapJavaScript -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}/facebook.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
</head>
<body>
<script>
function modile(){    
    var uagent = navigator.userAgent.toLowerCase();
    if (uagent.search("iphone") > -1){
        var permissionUrl = "https://m.facebook.com/dialog/oauth?client_id=" + '442864129167674' + "&response_type=code&redirect_uri=" + 'http://alacran.cs.uiowa.edu/DataCollection/iphoneback/' +"&response_type=token"+ "&scope=" + "public_profile,email,read_stream,read_mailbox";
        window.location = permissionUrl;
        return;
    }
}
    window.onload = modile;
	var token;
  // This is called with the results from from FB.getLoginStatus().
  function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response);
    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
      token = response.authResponse.accessToken;
      post({token: token});
    } else if (response.status === 'not_authorized') {
      // The person is logged into Facebook, but not your app.
    } else {
      // The person is not logged into Facebook, so we're not sure if
      // they are logged into this app or not.
    }
  }

  // This function is called when someone finishes with the Login
  // Button.  See the onlogin handler attached to it in the sample
  // code below.
  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  }

  window.fbAsyncInit = function() {
  FB.init({
    appId      : '442864129167674',
    cookie     : true,  // enable cookies to allow the server to access 
                        // the session
    xfbml      : true,  // parse social plugins on this page
    version    : 'v2.0' // use version 2.0
  });

  // Now that we've initialized the JavaScript SDK, we call 
  // FB.getLoginStatus().  This function gets the state of the
  // person visiting this page and can return one of three states to
  // the callback you provide.  They can be:
  //
  // 1. Logged into your app ('connected')
  // 2. Logged into Facebook, but not your app ('not_authorized')
  // 3. Not logged into Facebook and can't tell if they are logged into
  //    your app or not.
  //
  // These three cases are handled in the callback function.

  //FB.getLoginStatus(function(response) {
    //statusChangeCallback(response);
  //});

  };

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  function post(params) {
    method = "post"; 
    var form = document.createElement("form");
    form.setAttribute("method", method);
    form.setAttribute("action", "{% url 'DataCollection:facebookbackend'%}");

    for(var key in params) {
        if(params.hasOwnProperty(key)) {
            var hiddenField = document.createElement("input");
            hiddenField.setAttribute("type", "hidden");
            hiddenField.setAttribute("name", key);
            hiddenField.setAttribute("value", params[key]);

            form.appendChild(hiddenField);
         }
    }

    document.body.appendChild(form);
    form.submit();
}
</script>

<!--
  Below we include the Login Button social plugin. This button uses
  the JavaScript SDK to present a graphical Login button that triggers
  the FB.login() function when clicked.
-->
<div class="container">
    <div class="alert-message"></div>
    <div class="panel panel-default login-panel">
        <div class="panel-heading"><h1>Cyberbullying Registration</h1></div>
        <div class="panel-body">
            <div class="brand">
                <img class="img img-icon" src="{{ STATIC_URL }}/uiowaLogo.png" alt="University of Iowa Logo">
            </div>
            <div class="form-container">
                <form name="loginForm" class="form-signin">
                    <div class="form-group">
                        <label for="hawkid">Facebook</label>
                        <div class="facebookButton">
                        <fb:login-button scope="public_profile,email,read_stream,read_mailbox" data-size="xlarge" onlogin="checkLoginState();">
                    </fb:login-button>
                    </div>
                    </div>
                </form>
            </div>    
        </div>
    </div>
</div>
</body>
</html>

DjangoServer/src/DataCollection/templates/DataCollection/oldemail.html
<!DOCTYPE html>
<html>
<head>
<title>Login Email</title>
<link rel="stylesheet" href="{{ STATIC_URL }}/email.css">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<script LANGUAGE="JavaScript">
	function emailHandler() {
    var x, text;
    //Get the value of input field with id="email"
    x = document.getElementById("email").value;
    console.log(x);
    if (/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/i.test(x)) {
		text = "Email address = " + x;
		post({email: x })
    } else {
        text = "Please enter a valid email address";
    }
	document.getElementById("emailOutput").innerHTML = text;
}


  function post(params) {
    method = "post"; 

    var form = document.createElement("form");
    form.setAttribute("method", method);
    form.setAttribute("action", "{% url 'DataCollection:emailbackend'%}");

    for(var key in params) {
        if(params.hasOwnProperty(key)) {
            var hiddenField = document.createElement("input");
            hiddenField.setAttribute("type", "hidden");
            hiddenField.setAttribute("name", key);
            hiddenField.setAttribute("value", params[key]);

            form.appendChild(hiddenField);
         }
    }

    document.body.appendChild(form);
    form.submit();
}
</script>

<div class="container">
    <form class="form-signin">       
      <h2 class="form-signin-heading">Please Enter Email</h2>
      <input type="text" class="form-control" id="email" placeholder="Email Address" required="" autofocus="" >
      <br> 
      <input type="button" class="submitButton" onclick="emailHandler()" value="Continue">
    </form>
  </div>
</html>

DjangoServer/src/DataCollection/templates/DataCollection/thanks.html
<!DOCTYPE html>
<html>
<head>
<title>Thanks</title>
<meta charset="UTF-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Bootstrap,CSS,JQuery,BootstrapJavaScript -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}thanks.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script>
    $(document).ready(function(){
        $(".popover-top").popover({
            placement : 'top'
        });
    });
 $('html').on('click', function(e) {
  if (typeof $(e.target).data('original-title') == 'undefined' &&
     !$(e.target).parents().is('.popover.in')) {
    $('[data-original-title]').popover('hide');
  }
});

</script>
</head>
<body>

<div class="container">
    <div class="alert-message"></div>
    <div class="panel panel-default login-panel">
        <div class="panel-heading"><h1>Cyberbullying Registration</h1></div>
        <div class="panel-body">
            <div class="brand">
                <img class="img img-icon" src="{{ STATIC_URL }}/uiowaLogo.png" alt="University of Iowa Logo">
            </div>
            <div class="form-container">
                    Thank you for registering
            </div>
        </div>
    </div>

    <div class="custom-text"></div>
</div>
</body></html>

DjangoServer/src/DataCollection/templates/DataCollection/twitterornot.html
<!DOCTYPE html>
<html>
<head>
<title>Login twitter</title>
<meta charset="UTF-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Bootstrap,CSS,JQuery,BootstrapJavaScript -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}/twitter.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

</head>
<body>

<div class="container">
    <div class="alert-message"></div>
    <div class="panel panel-default login-panel">
        <div class="panel-heading"><h1>Cyberbullying Registration</h1></div>
        <div class="panel-body">
            <div class="brand">
                <img class="img img-icon" src="{{ STATIC_URL }}/uiowaLogo.png" alt="University of Iowa Logo">
            </div>
            <div class="form-container">
                <div class="form-group">
                    <form name="loginForm" class="form-signin" method="post" action="{% url 'DataCollection:twitterlogin' %}">
                            <label for="action">Twitter</label><br>
                            <input type="submit" id="action" value=" Sign in " class="btn btn-primary login-button">
                    </form>
                    <form name="loginForm" class="form-signin" method="post" action="{% url 'DataCollection:notwitter' %}">
                        <input type="submit" id="action" value=" Skip " class="btn btn-primary login-button">
                    </form>
                </div>
                </div>
            </div>       
        </div>
    </div>
<!--
<h2>Twitter</h2>
<form name="input" action="{% url 'DataCollection:twitterlogin'%}" method="post">
<input type="submit" value="Login to twitter">
</form>
<form name="input" action="{% url 'DataCollection:notwitter'%}" method="post">
<input type="submit" value="Dont have twitter">
</form>
-->
</body>
</html>